from pydantic import Field
from typing import Any
from .base import SchemaModel

class DualResponse(SchemaModel):
    """
    A wrapper schema to hold both a conversational reply and structured data.
    """
    chat_reply: str = Field(description="The conversational reply to the user.")
    generated_data: Any = Field(description="The structured data generated by the LLM.")
