from app.prompts.architect_templates import (
    ARCHITECT_INSTRUCTION,
    ARCHITECT_USER_TEMPLATE,
    CHAR_ANALYSIS_INSTRUCTION,
    CHAR_ANALYSIS_USER_TEMPLATE,
    POPULATE_INSTRUCTION,
    POPULATE_WITH_ANALYSIS_TEMPLATE,
    SHEET_GENERATOR_SYSTEM_PROMPT,
)
from app.prompts.templates import (
    SHARED_RULES_SYSTEM_PROMPT,
    VOCABULARY_ANALYSIS_INSTRUCTION,
    VOCABULARY_JSON_INSTRUCTION,
    VOCABULARY_GROUP_INSTRUCTION,
    EXTRACT_ENGINE_INSTRUCTION,
    EXTRACT_PROCEDURE_INSTRUCTION,
    GENERATE_MECHANICS_INSTRUCTION,
    IDENTIFY_RULE_CATEGORIES_INSTRUCTION,
    EXTRACT_RULE_CATEGORY_INSTRUCTION,
    EXTRACT_INVARIANTS_INSTRUCTION,
    ANALYZE_WORLD_INSTRUCTION,
    GENERATE_WORLD_INSTRUCTION,
    OPENING_CRAWL_PROMPT,
    JIT_SIMULATION_TEMPLATE,
)

__all__ = [
    # Architect / Sheet Generation
    "SHEET_GENERATOR_SYSTEM_PROMPT",
    "ARCHITECT_USER_TEMPLATE",
    "ARCHITECT_INSTRUCTION",
    "CHAR_ANALYSIS_USER_TEMPLATE",
    "CHAR_ANALYSIS_INSTRUCTION",
    "POPULATE_WITH_ANALYSIS_TEMPLATE",
    "POPULATE_INSTRUCTION",
    
    # Rules & Extraction (Forked Context)
    "SHARED_RULES_SYSTEM_PROMPT",
    "VOCABULARY_ANALYSIS_INSTRUCTION",
    "VOCABULARY_JSON_INSTRUCTION",
    "VOCABULARY_GROUP_INSTRUCTION",
    "EXTRACT_ENGINE_INSTRUCTION",
    "EXTRACT_PROCEDURE_INSTRUCTION",
    "GENERATE_MECHANICS_INSTRUCTION",
    "IDENTIFY_RULE_CATEGORIES_INSTRUCTION",
    "EXTRACT_RULE_CATEGORY_INSTRUCTION",
    "EXTRACT_INVARIANTS_INSTRUCTION",
    
    # World Gen
    "ANALYZE_WORLD_INSTRUCTION",
    "GENERATE_WORLD_INSTRUCTION",
    "OPENING_CRAWL_PROMPT",
    
    # Gameplay
    "JIT_SIMULATION_TEMPLATE",
]
