from app.prompts.architect_templates import (
    ARCHITECT_INSTRUCTION,
    ARCHITECT_USER_TEMPLATE,
    CHAR_ANALYSIS_INSTRUCTION,
    CHAR_ANALYSIS_USER_TEMPLATE,
    POPULATE_INSTRUCTION,
    POPULATE_WITH_ANALYSIS_TEMPLATE,
    SHEET_GENERATOR_SYSTEM_PROMPT,
)
from app.prompts.templates import (
    VOCABULARY_ANALYSIS_PROMPT,
    VOCABULARY_EXTRACTION_PROMPT,
    EXTRACT_INVARIANTS_INSTRUCTION,
    ANALYZE_WORLD_INSTRUCTION,
    EXTRACT_PROCEDURE_INSTRUCTION,
    GENERATE_MECHANICS_INSTRUCTION,
    GENERATE_WORLD_INSTRUCTION,
    IDENTIFY_MODES_INSTRUCTION,
    JIT_SIMULATION_TEMPLATE,
    OPENING_CRAWL_PROMPT,
    TEMPLATE_GENERATION_SYSTEM_PROMPT,
)

__all__ = [
    # Architect / Sheet Generation
    "SHEET_GENERATOR_SYSTEM_PROMPT",
    "ARCHITECT_USER_TEMPLATE",
    "ARCHITECT_INSTRUCTION",
    "CHAR_ANALYSIS_USER_TEMPLATE",
    "CHAR_ANALYSIS_INSTRUCTION",
    "POPULATE_WITH_ANALYSIS_TEMPLATE",
    "POPULATE_INSTRUCTION",
    # Rules & World Generation
    "TEMPLATE_GENERATION_SYSTEM_PROMPT",
    "IDENTIFY_MODES_INSTRUCTION",
    "EXTRACT_PROCEDURE_INSTRUCTION",
    "GENERATE_MECHANICS_INSTRUCTION",
    "ANALYZE_WORLD_INSTRUCTION",
    "GENERATE_WORLD_INSTRUCTION",
    "OPENING_CRAWL_PROMPT",
    "JIT_SIMULATION_TEMPLATE",
    "VOCABULARY_ANALYSIS_PROMPT",
    "VOCABULARY_EXTRACTION_PROMPT",

    "EXTRACT_INVARIANTS_INSTRUCTION",
]
